- name: "Read data files"
  hosts: "{{ target_host | default('domain:extensions') }}"
  connection: local
  tasks:
    - name: Load configuration files
      include_vars:
        file: "{{ item }}"
      loop:
        - "{{ data_path }}/dc.json"
        - "{{ data_path }}/windows_common.yml"
      run_once: true

    - name: save all variables as Facts
      set_fact:
        lab: "{{ lab }}"
        windows_config_loaded: true
        hostname: "{{ hostname }}"
        domain: "{{ domain }}"
        domain_username: "{{ domain_username }}"
        domain_password: "{{ domain_password }}"
        domain_server: "{{ domain_server }}"
        ad_users: "{{ ad_users }}"
        ad_ou: "{{ ad_ou }}"
        ad_groups: "{{ ad_groups }}"
        gmsa: "{{ gmsa }}"
        acls: "{{ acls }}"
        ServiceAccounts: "{{ ServiceAccounts }}"
        cacheable: yes
      run_once: true
