---
- import_playbook: windows_config.yml
  when: not windows_config_loaded | default(false)

- import_playbook: windows_root_OU.yml
- import_playbook: windows_child_OU.yml
- import_playbook: windows_groups.yml
- import_playbook: windows_gmsa.yml
- import_playbook: windows_users.yml
- import_playbook: windows_services_accounts.yml
- import_playbook: windows_dsacls.yml

- name: Configuration des groupes et utilisateurs de l'Olympe
  hosts: pantheon-dc01
  tasks:
    - name: Afficher le résumé de la configuration
      debug:
        msg: |
          Configuration terminée :
          - OUs racine créées : {{ ou_root_creation.results | map(attribute='item.key') | list }}
          - OUs enfants créées : {{ ou_children_creation.results | map(attribute='item.key') | list }}
          - Groupes créés : {{ groups_creation.results | map(attribute='item.key') | list }}
          - gMSA créés : {{ gmsa_creation.results | map(attribute='item.key') | list }}
          - Utilisateurs créés : {{ users_creation.results | map(attribute='item.key') | list }}
          - ACLs configurées : {{ acls.keys() | list }}