---
- import_playbook: windows_config.yml
  when: not windows_config_loaded | default(false)

- name: Configuration du Colisée
  hosts: pantheon-dc01
  tasks:
    - name: Créer le répertoire C:\coliseum
      win_file:
        path: C:\coliseum
        state: directory

    - name: Changer le  propriétaire du path coliseum
      ansible.windows.win_owner:
        path: C:\coliseum
        user: "PANTHEON\\athena"
        recurse: true

    - name: Donner tout les droits à cronos sur le répertoire coliseum
      win_acl:
        path: C:\coliseum
        user: "PANTHEON\\cronos"
        rights: FullControl
        type: allow
        state: present
        inherit: ContainerInherit,ObjectInherit

    - name: Vérifier l'existence du script ColiseumTasks.ps1
      win_file:
        path: C:\coliseum\ColiseumTasks.ps1
        state: touch
      register: script_check

    - name: Update Local Security Policy to allow users to run scheduled tasks
      ansible.windows.win_user_right:
        name: SeBatchLogonRight
        users:
          - PANTHEON\athena
          - PANTHEON\cronos
        action: add

    - name: Créer la tâche planifiée pour Athena
      community.windows.win_scheduled_task:
        name: AthenaScript
        description: Run a PowerShell script
        actions:
          - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
            arguments: -ExecutionPolicy Unrestricted -NonInteractive -File C:\coliseum\ColiseumTasks.ps1
        triggers:
          - type: daily
            start_boundary: '2025-01-01T00:00:00'
            repetition:
              interval: PT1M
              duration: PT24H
        username: PANTHEON\athena
        password: "Str@t3g1cM1nd!2024"
        logon_type: s4u
#       logon_type: password
        multiple_instances: 0
      tags: 
        - createsch


#   - name: Change above task to run under a domain user account, storing the passwords
#     community.windows.win_scheduled_task:
#       name: AthenaScript
#       username: PANTHEON\athena
#       password: "Str@t3g1cM1nd!2024"
#       logon_type: password


