---
- import_playbook: windows_config.yml
  when: not windows_config_loaded | default(false)

- name: Autoriser l'accès distant RDP aux dieux et cronos
  hosts: extensions
  tasks:
#    - name: Ajouter les dieux du domaine et cronos au groupe local Remote Desktop Users
    - name: Ajouter les dieux du domaine et persephone au groupe local Remote Desktop Users
      win_group_membership:
        name: "Remote Desktop Users"
        members:
#          - "PANTHEON\\cronos"
          - "OLYMPE-GODS"
        state: present

    - name: Ajouter les dieux du domaine et cronos au groupe local Remote Management Users
      win_group_membership:
        name: "Remote Management Users"
        members:
          - "PANTHEON\\cronos"
          - "OLYMPE-GODS"
        state: present

    - name: Accorder le droit de connexion à distance aux membres du groupe Remote Desktop Users
      win_user_right:
        name: SeRemoteInteractiveLogonRight
        users:
          - "Remote Desktop Users"
        action: add


- name: Autoriser l'accès distant RDP a persephone
  hosts: pantheon-enfers
  tasks:
    - name: Ajouter persephone au groupe local Remote Desktop Users
      win_group_membership:
        name: "Remote Desktop Users"
        members:
          - "PANTHEON\\persephone"
        state: present
    - name: Accorder le droit de connexion à distance aux membres du groupe Remote Desktop Users
      win_user_right:
        name: SeRemoteInteractiveLogonRight
        users:
          - "Remote Desktop Users"
        action: add
