---
- import_playbook: windows_config.yml
  when: not windows_config_loaded | default(false)

- name: Configuration DPAPI - Injection des credentials sur pantheon-enfers
  hosts: pantheon-dc01
  tasks:
    - name: Ajouter le droit SeBatchLogonRight pour hera
      ansible.windows.win_user_right:
        name: SeBatchLogonRight
        users:
          - PANTHEON\hera
        action: add

    - name: Supprimer l'ancienne tâche planifiée si elle existe
      community.windows.win_scheduled_task:
        name: Hera-DPAPI-Creds
        state: absent
      ignore_errors: yes

    - name: Créer une tâche planifiée quotidienne pour injecter les credentials DPAPI de Hera
      community.windows.win_scheduled_task:
        name: Hera-DPAPI-Creds
        description: "Injection quotidienne des credentials DPAPI avec cmdkey pour hera"
        actions:
          - path: C:\Windows\System32\cmd.exe
            arguments: '/c cmdkey /add:pantheon.god /user:hera /pass:Qu33n0fG0ds!2025'
        triggers:
          - type: daily
            start_boundary: '2025-01-01T08:00:00'
            repetition:
              interval: PT1M
              duration: PT24H
        username: PANTHEON\hera
        password: "Qu33n0fG0ds!2025"
        logon_type: s4u
        enabled: true
        multiple_instances: 0
