---
- import_playbook: config.yml

- name: Configuration des groupes et utilisateurs de l'Olympe
  hosts: pantheon-dc01
  gather_facts: true
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: plaintext
    ansible_winrm_server_cert_validation: ignore
    ansible_user: Administrator
    ansible_password: "{{ lab.hosts.dc01.local_admin_password }}"
    hostname: "{{ lab.hosts.dc01.hostname }}"
    domain: "{{ lab.hosts.dc01.domain }}"
    domain_username: "{{ domain }}\\Administrator"
    domain_password: "{{ lab.hosts.dc01.local_admin_password }}"
    domain_server: "{{ lab.hosts.dc01.hostname }}.{{ domain }}"
    ad_users: "{{ lab.domains[lab.hosts.dc01.domain].users }}"
    ad_ou: "{{ lab.domains[lab.hosts.dc01.domain].organisation_units }}"
    ad_groups: "{{ lab.domains[lab.hosts.dc01.domain].groups }}"
    gmsa: "{{ lab.domains[lab.hosts.dc01.domain].gmsa }}"
    acls: "{{ lab.domains[lab.hosts.dc01.domain].acls }}"

  tasks:
    - name: Créer les OUs de premier niveau
      microsoft.ad.ou:
        name: "{{ item.key }}"
        path: "{{ lab.hosts.dc01.path }}"
        description: "{{ item.value.description }}"
        state: present
        domain_username: "{{ domain_username }}"
        domain_password: "{{ domain_password }}"
        domain_server: "{{ domain_server }}"
      with_dict: "{{ ad_ou }}"
      register: ou_root_creation
      no_log: true

    - name: Créer les OUs enfants
      microsoft.ad.ou:
        name: "{{ item.key }}"
        path: "{{ item.value.path }}"
        description: "{{ item.value.description }}"
        state: present
        domain_username: "{{ domain_username }}"
        domain_password: "{{ domain_password }}"
        domain_server: "{{ domain_server }}"
      with_dict: "{{ ad_ou.ENFERS.children }}"
      register: ou_children_creation
      no_log: true

    - name: Créer les groupes du domaine
      microsoft.ad.group:
        name: "{{ item.key }}"
        path: "{{ item.value.path }}"
        scope: "{{ item.value.type | default('global') }}"
        category: security
        description: "{{ item.value.description | default('') }}"
        state: present
        domain_username: "{{ domain_username }}"
        domain_password: "{{ domain_password }}"
        domain_server: "{{ domain_server }}"
      with_dict: "{{ ad_groups }}"
      register: groups_creation
      no_log: true

    - name: Créer la KDS Root Key
      win_shell: |
        $effectiveTime = (Get-Date).AddHours(-10)
        Add-KdsRootKey -EffectiveTime $effectiveTime
      register: kds_key
      no_log: true

    - name: Créer les comptes gMSA
      win_shell: |
        $groupDN = (Get-ADGroup -Identity "{{ item.value.PrincipalsAllowedToRetrieveManagedPassword[0] }}").DistinguishedName
        $spns = @({{ item.value.gMSA_SPNs | map('regex_replace', '^(.*)$', '"$1"') | join(', ') }})
        if (-not (Get-ADServiceAccount -Filter "Name -eq '{{ item.value.gMSA_Name }}'" -ErrorAction SilentlyContinue)) {
          New-ADServiceAccount -Name "{{ item.value.gMSA_Name }}" `
            -Path "OU=OLYMPIENS,{{ lab.hosts.dc01.path }}" `
            -PrincipalsAllowedToRetrieveManagedPassword $groupDN `
            -DNSHostName "{{ item.value.gMSA_FQDN }}" `
            -ServicePrincipalNames $spns `
            -Enabled $true
        }
      with_dict: "{{ gmsa }}"
      register: gmsa_creation
      no_log: true

    - name: Créer les utilisateurs du domaine
      microsoft.ad.user:
        name: "{{ item.key }}"
        firstname: "{{ item.value.firstname }}"
        surname: "{{ item.value.surname }}"
        password: "{{ item.value.password }}"
        password_never_expires: yes
        state: present
        path: "{{ item.value.path }}"
        description: "{{ item.value.description }}"
        groups:
          set: "{{ item.value.groups }}"
        enabled: "{{ item.value.enabled | default(true) }}"
        domain_username: "{{ domain_username }}"
        domain_password: "{{ domain_password }}"
        domain_server: "{{ domain_server }}"
      with_dict: "{{ ad_users }}"
      register: users_creation
      no_log: true

    - name: Configurer les ACLs
      win_shell: |
        {% for acl_name, acl in acls.items() %}
        $targetDN = {% if acl.to == 'ENFERS' or acl.to == 'TARTARE' or acl.to == 'ELYSEE' %}
          (Get-ADOrganizationalUnit -Filter "Name -eq '{{ acl.to }}'").DistinguishedName
        {% else %}
          (Get-ADGroup -Identity "{{ acl.to }}").DistinguishedName
        {% endif %}
        $acl = Get-Acl "AD:$targetDN"
        $identity = {% if acl.for in gmsa.keys() %}
          (Get-ADServiceAccount -Identity "{{ gmsa[acl.for].gMSA_Name }}").SID
        {% else %}
          (Get-ADUser -Identity "{{ acl.for }}").SID
        {% endif %}
        $adRights = [System.DirectoryServices.ActiveDirectoryRights]"{{ acl.right }}"
        $type = [System.Security.AccessControl.AccessControlType]"Allow"
        $inheritance = [System.DirectoryServices.ActiveDirectorySecurityInheritance]"{{ acl.inheritance }}"
        $rule = New-Object System.DirectoryServices.ActiveDirectoryAccessRule($identity, $adRights, $type, $inheritance)
        $acl.AddAccessRule($rule)
        Set-Acl -AclObject $acl -Path "AD:$targetDN"
        {% endfor %}
      register: acl_setup
      no_log: true

    - name: Afficher le résumé de la configuration
      debug:
        msg: |
          Configuration terminée :
          - OUs racine créées : {{ ou_root_creation.results | map(attribute='item.key') | list }}
          - OUs enfants créées : {{ ou_children_creation.results | map(attribute='item.key') | list }}
          - Groupes créés : {{ groups_creation.results | map(attribute='item.key') | list }}
          - gMSA créés : {{ gmsa_creation.results | map(attribute='item.key') | list }}
          - Utilisateurs créés : {{ users_creation.results | map(attribute='item.key') | list }}
          - ACLs configurées : {{ acls.keys() | list }}  