Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname = "okeanos"
    config.vm.network "private_network", ip: "192.168.56.15"
  
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/vagrant/ansible/playbooks/linux_okeanos.yml"
      ansible.inventory_path = "/vagrant/ansible/inventory/linux_inventory.yml"
    end
  end
  