---
- import_playbook: config.yml

- name: Configuration du CA01
  hosts: pantheon-ca01
  gather_facts: true
  vars:
    domain: "{{ lab.hosts.ca01.domain }}"
    domain_admin_user: "{{ domain }}\\administrator"
    domain_admin_password: "{{ lab.hosts.ca01.local_admin_password }}"
  tasks:
    - name: Configurer le DNS pour pointer vers DC01
      win_dns_client:
        adapter_name: "Ethernet 2"
        dns_servers:
          - 192.168.56.11

    - name: Attendre que le DNS soit effectif
      pause:
        seconds: 10

    - name: Joindre le domaine pantheon.god
      ansible.windows.win_domain_membership:
        dns_domain_name: "{{ domain }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
      register: domain_state

    - name: Redémarrer après jointure au domaine
      ansible.windows.win_reboot:
        msg: "Redémarrage après jointure au domaine"
        pre_reboot_delay: 30
        post_reboot_delay: 30
        reboot_timeout: 3600
      when: domain_state.reboot_required


