---
- name: Configuration du DC01
  hosts: dc01
  gather_facts: true
  vars_files:
    - ../vars/default.yml
    - ../vars/linux_gods_users.yml

  tasks:
    - name: Installer les rôles AD-Domain-Services et DNS
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        state: present
      register: ad_install

    - name: Définir le mot de passe de l'administrateur local
      win_user:
        name: Administrator
        password: "Pantheon@2024"
        state: present

    - name: Configurer le DNS local
      win_shell: |
        Set-DnsClientServerAddress -InterfaceAlias "Ethernet 2" -ServerAddresses "127.0.0.1"
        if (-not (Get-DnsServerZone -Name "pantheon.god" -ErrorAction SilentlyContinue)) {
          Add-DnsServerPrimaryZone -Name "pantheon.god" -ZoneFile "pantheon.god.dns" -DynamicUpdate None
        }
        if (-not (Get-DnsServerResourceRecord -ZoneName "pantheon.god" -Name "@" -ErrorAction SilentlyContinue)) {
          Add-DnsServerResourceRecordA -Name "@" -ZoneName "pantheon.god" -IPv4Address "192.168.56.11"
        }
      register: dns_config

    - name: Créer l'enregistrement DNS pour dc01
      win_shell: |
        $zoneName = "pantheon.god"
        $recordName = "dc01"
        $ipAddress = "192.168.56.11"
        
        # Vérifier si l'enregistrement existe déjà
        $existingRecord = Get-DnsServerResourceRecord -ZoneName $zoneName -Name $recordName -ErrorAction SilentlyContinue
        
        if (-not $existingRecord) {
            # Créer l'enregistrement A
            Add-DnsServerResourceRecordA -Name $recordName -ZoneName $zoneName -IPv4Address $ipAddress -CreatePtr
            Write-Host "Enregistrement DNS créé pour $recordName.$zoneName"
        } else {
            Write-Host "L'enregistrement DNS existe déjà pour $recordName.$zoneName"
        }
      register: dns_record

    - name: Créer le dossier NTDS
      win_file:
        path: C:\Windows\NTDS
        state: directory

    - name: Créer le domaine
      win_domain:
        domain_netbios_name: PANTHEON
        dns_domain_name: pantheon.god
        safe_mode_password: "{{ ad_safe_mode_password }}"
      register: check_domain

    - name: Redémarrer après création du domaine
      win_reboot:
        reboot_timeout: 900
        post_reboot_delay: 300
      when: check_domain.changed

    - name: Promouvoir le serveur en contrôleur de domaine
      win_domain_controller:
        dns_domain_name: pantheon.god
        safe_mode_password: "{{ ad_safe_mode_password }}"
        database_path: C:\Windows\NTDS
        sysvol_path: C:\Windows\SYSVOL
        state: domain_controller
        domain_admin_user: .\Administrator
        domain_admin_password: Pantheon@2024
      register: check_domain_controller

    - name: Redémarrer après promotion en contrôleur de domaine
      win_reboot:
        reboot_timeout: 900
        post_reboot_delay: 100
      when: check_domain_controller.changed

    - name: S'assurer que l'administrateur est dans le groupe Enterprise Admins
      win_domain_group_membership:
        name: "Enterprise Admins"
        members:
          - Administrator
        state: present

    - name: S'assurer que l'administrateur est dans le groupe Domain Admins
      win_domain_group_membership:
        name: "Domain Admins"
        members:
          - Administrator
        state: present

    - name: Créer les utilisateurs dieux dans l'AD
      win_domain_user:
        name: "{{ item.name | lower | replace('é', 'e') | replace('è', 'e') | replace('ê', 'e') | replace('à', 'a') | replace('â', 'a') | replace('ï', 'i') | replace('î', 'i') | replace('ô', 'o') | replace('ù', 'u') | replace('ç', 'c') | replace(' ', '_') }}"
        password: "{{ item.password }}"
        state: present
        groups:
          - Domain Users
        attributes:
          description: "{{ item.name }} - Dieu de l'Olympe"
      loop: "{{ linux_users_gods }}"

    - name: Ajouter Zeus au groupe Enterprise Admins
      win_domain_group_membership:
        name: "Enterprise Admins"
        members:
          - zeus
        state: present

    - name: Ajouter Zeus au groupe Domain Admins
      win_domain_group_membership:
        name: "Domain Admins"
        members:
          - zeus
        state: present 