---
- name: Configuration du DC02
  hosts: dc02
  gather_facts: true
  vars_files:
    - ../vars/default.yml
    - ../vars/linux_gods_users.yml

  tasks:
    - name: Installer les rôles AD-Domain-Services et DNS
      win_feature:
        name:
          - AD-Domain-Services
          - DNS
        include_management_tools: yes
        state: present
      register: ad_install

    - name: Définir le mot de passe de l'administrateur local
      win_user:
        name: Administrator
        password: "Pantheon@2024"
        state: present

    - name: Configurer le DNS local
      win_shell: |
        Set-DnsClientServerAddress -InterfaceAlias "Ethernet 2" -ServerAddresses "192.168.56.11"
        if (-not (Get-DnsServerZone -Name "pantheon.god" -ErrorAction SilentlyContinue)) {
          Add-DnsServerPrimaryZone -Name "pantheon.god" -ZoneFile "pantheon.god.dns" -DynamicUpdate None
        }
        if (-not (Get-DnsServerResourceRecord -ZoneName "pantheon.god" -Name "@" -ErrorAction SilentlyContinue)) {
          Add-DnsServerResourceRecordA -Name "@" -ZoneName "pantheon.god" -IPv4Address "192.168.56.12"
        }
      register: dns_config

    - name: Créer l'enregistrement DNS pour dc02
      win_shell: |
        $zoneName = "pantheon.god"
        $recordName = "dc02"
        $ipAddress = "192.168.56.12"
        $existingRecord = Get-DnsServerResourceRecord -ZoneName $zoneName -Name $recordName -ErrorAction SilentlyContinue
        if (-not $existingRecord) {
            Add-DnsServerResourceRecordA -Name $recordName -ZoneName $zoneName -IPv4Address $ipAddress -CreatePtr
        }
      register: dns_record

    - name: Créer le dossier NTDS
      win_file:
        path: C:\Windows\NTDS
        state: directory

    - name: Promouvoir le serveur en contrôleur de domaine
      win_domain_controller:
        dns_domain_name: pantheon.god
        safe_mode_password: "{{ ad_safe_mode_password }}"
        database_path: C:\Windows\NTDS
        sysvol_path: C:\Windows\SYSVOL
        state: domain_controller
        domain_admin_user: .\Administrator
        domain_admin_password: Pantheon@2024
      register: check_domain_controller

    - name: Redémarrer après promotion en contrôleur de domaine
      win_reboot:
        reboot_timeout: 900
        post_reboot_delay: 100
      when: check_domain_controller.changed

    - name: S'assurer que l'administrateur est dans le groupe Enterprise Admins
      win_domain_group_membership:
        name: "Enterprise Admins"
        members:
          - Administrator
        state: present

    - name: S'assurer que l'administrateur est dans le groupe Domain Admins
      win_domain_group_membership:
        name: "Domain Admins"
        members:
          - Administrator
        state: present

    # --- ADCS ---
    - name: Installer le rôle ADCS
      win_feature:
        name: AD-Certificate
        include_management_tools: yes
        state: present
      register: adcs_install

    - name: Configurer ADCS
      win_shell: |
        Install-AdcsCertificationAuthority -CAType EnterpriseRootCA -CryptoProviderName "RSA#Microsoft Software Key Storage Provider" -KeyLength 2048 -HashAlgorithmName SHA256 -ValidityPeriod Years -ValidityPeriodUnits 5 -DatabaseDirectory "C:\Windows\System32\CertLog" -LogDirectory "C:\Windows\System32\CertLog" -Force
      when: adcs_install.changed

    - name: Installer le module PSPKI
      win_shell: |
        Install-Module PSPKI -Force

    - name: Configurer les permissions sur le CA
      win_shell: |
        Import-Module PSPKI
        $caHostname = Get-CertificationAuthority | Select-Object -ExpandProperty ComputerName
        Get-CertificationAuthority "$caHostname" | Get-CertificationAuthorityAcl | Add-CertificationAuthorityAcl -Identity "pantheon.god\Administrator" -AccessType "Allow" -AccessMask "ManageCa" | Set-CertificationAuthorityAcl -RestartCA
      register: ca_permissions 