- import_playbook: config.yml

- name: Générer et configurer certificat LDAPS sur DC Windows
  hosts: pantheon-dc01
  gather_facts: false
  vars:
    server_type: "dc01"
    domain: "{{ lab.hosts[server_type].domain }}"
    hostname: "{{ lab.hosts[server_type].hostname }}"
    domain_admin_user: "{{ domain }}\\administrator"
    domain_admin_password: "{{ lab.hosts[server_type].local_admin_password }}"

    cert_signing_ca_hostname: "pantheon-ca01"
    cert_signing_ca_user: "{{ domain_admin_user }}"
    cert_signing_ca_password: "{{ domain_admin_password }}"
    cert_signing_ca_common_name: "{{ cert_signing_ca_hostname }}-CA"
    cert_signing_ca_fqdn: "{{ cert_signing_ca_hostname }}.{{ domain | lower }}"

    cert_private_key_path: "C:\\Windows\\Temp\\ldaps.key"
    cert_subject: "CN={{ hostname }}.{{ domain }}"
    cert_csr_to_file: true
    cert_signing_ca_csr_path: "C:\\Windows\\Temp\\ldaps.req"

    cert_certificate_to_file: true
    cert_certificate_path: "C:\\Windows\\Temp\\ldaps.crt"
    cert_certificate_to_variable: true
    cert_signing_ca_shell_type: "powershell"

  roles:
    - role: trippsc2.adcs.signed_certificate

  tasks:
    - name: Importer le certificat signé dans le magasin LocalMachine\My
      win_shell: |
        $certPath = "{{ cert_certificate_path }}"
        Import-Certificate -FilePath $certPath -CertStoreLocation Cert:\LocalMachine\My
      args:
        executable: powershell.exe

    - name: Obtenir le thumbprint du certificat importé
      win_shell: |
        $cert = Get-ChildItem Cert:\LocalMachine\My | Where-Object { $_.Subject -like "*{{ hostname }}*" } | Select-Object -First 1
        Write-Output $cert.Thumbprint
      register: cert_thumbprint_raw

    - name: Nettoyer le thumbprint (sans espaces)
      set_fact:
        cert_thumbprint_nospaces: "{{ cert_thumbprint_raw.stdout | regex_replace(' ', '') }}"

    - name: Configurer le certificat LDAPS dans la registry
      win_regedit:
        path: 'HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Parameters'
        name: CertificateHash
        data: "{{ cert_thumbprint_nospaces }}"
        type: string

    - name: Configurer CertificateFlags à 0
      win_regedit:
        path: 'HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Parameters'
        name: CertificateFlags
        data: 0
        type: dword

    - name: Redémarrer le service Active Directory Domain Services (NTDS)
      win_service:
        name: NTDS
        state: restarted

