---
- name: Configuration du domaine Active Directory
  hosts: all
  gather_facts: true

- import_playbook: adds.yml
- import_playbook: dns.yml
- import_playbook: adcs_role.yml
- import_playbook: domain_objects.yml


