---
- import_playbook: windows_config.yml
  when: not windows_config_loaded | default(false)

- name: Configuration des groupes et utilisateurs de l'Olympe
  hosts: pantheon-dc01
  tasks:
    - name: Créer les utilisateurs du domaine
      microsoft.ad.user:
        name: "{{ item.key }}"
        firstname: "{{ item.value.firstname }}"
        surname: "{{ item.value.surname }}"
        password: "{{ item.value.password }}"
        description: "{{ item.value.description }}"
        path: "{{ item.value.path }}"
        state: present
        groups: 
          set:
            "{{ item.value.groups | join(',') }}"
      with_dict: "{{ ad_users }}"
      register: users_creation
      loop_control:
        label: "{{ item.key }}"

