---
- import_playbook: windows_config.yml

- name: Configuration des groupes et utilisateurs de l'Olympe
  hosts: pantheon-dc01
  gather_facts: true
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: plaintext
    ansible_winrm_server_cert_validation: ignore
    ansible_user: Administrator
    ansible_password: "{{ lab.hosts.dc01.local_admin_password }}"
    hostname: "{{ lab.hosts.dc01.hostname }}"
    domain: "{{ lab.hosts.dc01.domain }}"
    domain_username: "{{ domain }}\\Administrator"
    domain_password: "{{ lab.hosts.dc01.local_admin_password }}"
    domain_server: "{{ lab.hosts.dc01.hostname }}.{{ domain }}"
    ad_users: "{{ lab.domains[lab.hosts.dc01.domain].users }}"
    ad_ou: "{{ lab.domains[lab.hosts.dc01.domain].organisation_units }}"
    ad_groups: "{{ lab.domains[lab.hosts.dc01.domain].groups }}"
    gmsa: "{{ lab.domains[lab.hosts.dc01.domain].gmsa }}"
    acls: "{{ lab.domains[lab.hosts.dc01.domain].acls }}" 

  tasks:
    - name: Créer les utilisateurs du domaine
      microsoft.ad.user:
        name: "{{ item.key }}"
        firstname: "{{ item.value.firstname }}"
        surname: "{{ item.value.surname }}"
        password: "{{ item.value.password }}"
        password_never_expires: yes
        state: present
        path: "{{ item.value.path }}"
        description: "{{ item.value.description }}"
        groups:
          set: "{{ item.value.groups }}"
        enabled: "{{ item.value.enabled | default(true) }}"
        domain_username: "{{ domain_username }}"
        domain_password: "{{ domain_password }}"
        domain_server: "{{ domain_server }}"
      with_dict: "{{ ad_users }}"
      register: users_creation
      loop_control:
        label: "{{ item.key }}"

