---
- import_playbook: windows_config.yml

- name: Configuration des groupes et utilisateurs de l'Olympe
  hosts: pantheon-dc01
  gather_facts: true
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: plaintext
    ansible_winrm_server_cert_validation: ignore
    ansible_user: Administrator
    ansible_password: "{{ lab.hosts.dc01.local_admin_password }}"
    hostname: "{{ lab.hosts.dc01.hostname }}"
    domain: "{{ lab.hosts.dc01.domain }}"
    domain_username: "{{ domain }}\\Administrator"
    domain_password: "{{ lab.hosts.dc01.local_admin_password }}"
    domain_server: "{{ lab.hosts.dc01.hostname }}.{{ domain }}"
    ad_users: "{{ lab.domains[lab.hosts.dc01.domain].users }}"
    ad_ou: "{{ lab.domains[lab.hosts.dc01.domain].organisation_units }}"
    ad_groups: "{{ lab.domains[lab.hosts.dc01.domain].groups }}"
    gmsa: "{{ lab.domains[lab.hosts.dc01.domain].gmsa }}"
    acls: "{{ lab.domains[lab.hosts.dc01.domain].acls }}" 

  tasks:

    - name: Créer la KDS Root Key
      win_shell: |
        $effectiveTime = (Get-Date).AddHours(-10)
        Add-KdsRootKey -EffectiveTime $effectiveTime
      register: kds_key

    - name: Créer les comptes gMSA
      ansible.windows.win_powershell:
        script: |
          [CmdletBinding()]
          param (
              [String]
              $gMSA_Name,

              [String]
              $gMSA_FQDN,

              [String[]]
              $gMSA_SPNs,

              [String[]]
              $PrincipalsAllowedToRetrieveManagedPassword,

              [String]
              $Path
          )
          Import-Module ActiveDirectory
          Set-Location AD:
          
          try {
            $principals = $PrincipalsAllowedToRetrieveManagedPassword | ForEach-Object { 
              Get-ADGroup -Identity $_ 
            }
            
            $gmsa = Get-ADServiceAccount -Filter "Name -eq '$gMSA_Name'" -ErrorAction SilentlyContinue
            if ($gmsa) {
              # Mise à jour des SPNs
              $currentSPNs = (Get-ADServiceAccount -Identity $gMSA_Name -Properties ServicePrincipalNames).ServicePrincipalNames
              $newSPNs = $gMSA_SPNs | Where-Object { $currentSPNs -notcontains $_ }
              if ($newSPNs) {
                Set-ADServiceAccount -Identity $gMSA_Name -Add @{ServicePrincipalNames = $newSPNs}
              }
              
              # Mise à jour des autres propriétés
              Set-ADServiceAccount -Identity $gMSA_Name `
                -DNSHostName $gMSA_FQDN `
                -PrincipalsAllowedToRetrieveManagedPassword $principals `
                -Enabled $true `
                -Verbose
            } else {
              New-ADServiceAccount -Name $gMSA_Name `
                -Path $Path `
                -DNSHostName $gMSA_FQDN `
                -PrincipalsAllowedToRetrieveManagedPassword $principals `
                -ServicePrincipalNames $gMSA_SPNs `
                -Enabled $true `
                -Verbose
            }
          } catch {
            throw $_
          }
        parameters:
          gMSA_Name: "{{ item.value.gMSA_Name }}"
          gMSA_FQDN: "{{ item.value.gMSA_FQDN }}"
          gMSA_SPNs: "{{ item.value.gMSA_SPNs }}"
          PrincipalsAllowedToRetrieveManagedPassword: "{{ item.value.PrincipalsAllowedToRetrieveManagedPassword }}"
          Path: "OU=OLYMPIENS,{{ lab.hosts.dc01.path }}"
      with_dict: "{{ gmsa }}"
      register: gmsa_creation
      loop_control:
        label: "{{ item.key }}"

    - name: Afficher les détails de création du gMSA
      debug:
        msg: |
          Configuration du compte gMSA {{ item.item.key }} :
          - Nom : {{ item.item.value.gMSA_Name }}
          - FQDN : {{ item.item.value.gMSA_FQDN }}
          - SPNs : {{ item.item.value.gMSA_SPNs | join(', ') }}
          - Principaux autorisés : {{ item.item.value.PrincipalsAllowedToRetrieveManagedPassword | join(', ') }}
      loop: "{{ gmsa_creation.results }}"
      when: item.changed

