---
- import_playbook: windows_config.yml
  when: not windows_config_loaded | default(false)

- name: Configuration des groupes et utilisateurs de l'Olympe
  hosts: pantheon-dc01
  tasks:
    - name: Créer les OUs enfants
      microsoft.ad.ou:
        name: "{{ item.key }}"
        path: "{{ item.value.path | regex_replace('^OU=[^,]+,(.+)$', '\\1') }}"
        description: "{{ item.value.description }}"
        state: present
      with_dict: "{{ ad_ou.ENFERS.children }}"
      register: ou_children_creation
      loop_control:
        label: "{{ item.key }}"