---
all:
  children:
    linux_servers:
      hosts:
        linux:
          ansible_host: 192.168.56.10
          data_path: "{{ playbook_dir }}/../vars"
          playbook_path: "{{ playbook_dir }}"
  vars:
    ansible_user: vagrant
    ansible_private_key_file: "../../vagrant/linux/.vagrant/machines/linux/virtualbox/private_key"
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes
    ansible_become_method: sudo
    ansible_compatibility_mode: "2.0" 