---
all:
  children:
    domain:
      children:
        extensions:
          hosts:
            pantheon-dc01:
              ansible_host: 192.168.56.11
              data_path: "{{ playbook_dir }}/../vars"
            pantheon-enfer:
              ansible_host: 192.168.56.12
              data_path: "{{ playbook_dir }}/../vars"

  vars:
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: plaintext
    ansible_winrm_port: 5985 
